// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: admin_system.proto

package baseservice

import (
	"context"

	"github.com/DrReMain/cyber-ecosystem-server/rpc/admin_system/admin_system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDRes         = admin_system.BaseIDRes
	BaseRes           = admin_system.BaseRes
	CasbinBody        = admin_system.CasbinBody
	CasbinReq         = admin_system.CasbinReq
	CasbinRes         = admin_system.CasbinRes
	DepartmentBody    = admin_system.DepartmentBody
	DepartmentListReq = admin_system.DepartmentListReq
	DepartmentListRes = admin_system.DepartmentListRes
	EmailReq          = admin_system.EmailReq
	Empty             = admin_system.Empty
	IDReq             = admin_system.IDReq
	IDsReq            = admin_system.IDsReq
	ListReq           = admin_system.ListReq
	MenuBody          = admin_system.MenuBody
	MenuListReq       = admin_system.MenuListReq
	MenuListRes       = admin_system.MenuListRes
	PositionBody      = admin_system.PositionBody
	PositionListReq   = admin_system.PositionListReq
	PositionListRes   = admin_system.PositionListRes
	ResourceBody      = admin_system.ResourceBody
	RoleBody          = admin_system.RoleBody
	RoleFromMenuReq   = admin_system.RoleFromMenuReq
	RoleFromMenuRes   = admin_system.RoleFromMenuRes
	RoleFromRoleReq   = admin_system.RoleFromRoleReq
	RoleFromRoleRes   = admin_system.RoleFromRoleRes
	RoleListReq       = admin_system.RoleListReq
	RoleListRes       = admin_system.RoleListRes
	UserBody          = admin_system.UserBody
	UserListReq       = admin_system.UserListReq
	UserListRes       = admin_system.UserListRes

	BaseService interface {
		InitDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseRes, error)
	}

	defaultBaseService struct {
		cli zrpc.Client
	}
)

func NewBaseService(cli zrpc.Client) BaseService {
	return &defaultBaseService{
		cli: cli,
	}
}

func (m *defaultBaseService) InitDB(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseRes, error) {
	client := admin_system.NewBaseServiceClient(m.cli.Conn())
	return client.InitDB(ctx, in, opts...)
}
