// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin_system.proto

package casbinservice

import (
	"context"

	"github.com/DrReMain/cyber-ecosystem-server/rpc/admin_system/admin_system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDRes         = admin_system.BaseIDRes
	BaseRes           = admin_system.BaseRes
	CasbinBody        = admin_system.CasbinBody
	CasbinReq         = admin_system.CasbinReq
	CasbinRes         = admin_system.CasbinRes
	DepartmentBody    = admin_system.DepartmentBody
	DepartmentListReq = admin_system.DepartmentListReq
	DepartmentListRes = admin_system.DepartmentListRes
	EmailReq          = admin_system.EmailReq
	Empty             = admin_system.Empty
	IDReq             = admin_system.IDReq
	IDsReq            = admin_system.IDsReq
	ListReq           = admin_system.ListReq
	MenuBody          = admin_system.MenuBody
	MenuListReq       = admin_system.MenuListReq
	MenuListRes       = admin_system.MenuListRes
	PositionBody      = admin_system.PositionBody
	PositionListReq   = admin_system.PositionListReq
	PositionListRes   = admin_system.PositionListRes
	ResourceBody      = admin_system.ResourceBody
	RoleBody          = admin_system.RoleBody
	RoleFromMenuReq   = admin_system.RoleFromMenuReq
	RoleFromMenuRes   = admin_system.RoleFromMenuRes
	RoleFromRoleReq   = admin_system.RoleFromRoleReq
	RoleFromRoleRes   = admin_system.RoleFromRoleRes
	RoleListReq       = admin_system.RoleListReq
	RoleListRes       = admin_system.RoleListRes
	UserBody          = admin_system.UserBody
	UserListReq       = admin_system.UserListReq
	UserListRes       = admin_system.UserListRes

	CasbinService interface {
		QueryCasbinByRole(ctx context.Context, in *CasbinReq, opts ...grpc.CallOption) (*CasbinRes, error)
		QueryRoleByMenu(ctx context.Context, in *RoleFromMenuReq, opts ...grpc.CallOption) (*RoleFromMenuRes, error)
		QueryRoleByRole(ctx context.Context, in *RoleFromRoleReq, opts ...grpc.CallOption) (*RoleFromRoleRes, error)
	}

	defaultCasbinService struct {
		cli zrpc.Client
	}
)

func NewCasbinService(cli zrpc.Client) CasbinService {
	return &defaultCasbinService{
		cli: cli,
	}
}

func (m *defaultCasbinService) QueryCasbinByRole(ctx context.Context, in *CasbinReq, opts ...grpc.CallOption) (*CasbinRes, error) {
	client := admin_system.NewCasbinServiceClient(m.cli.Conn())
	return client.QueryCasbinByRole(ctx, in, opts...)
}

func (m *defaultCasbinService) QueryRoleByMenu(ctx context.Context, in *RoleFromMenuReq, opts ...grpc.CallOption) (*RoleFromMenuRes, error) {
	client := admin_system.NewCasbinServiceClient(m.cli.Conn())
	return client.QueryRoleByMenu(ctx, in, opts...)
}

func (m *defaultCasbinService) QueryRoleByRole(ctx context.Context, in *RoleFromRoleReq, opts ...grpc.CallOption) (*RoleFromRoleRes, error) {
	client := admin_system.NewCasbinServiceClient(m.cli.Conn())
	return client.QueryRoleByRole(ctx, in, opts...)
}
