// Code generated by ent, DO NOT EDIT.

package ent

import "time"

func (_m *DepartmentUpdate) SetNotNilUpdatedAt(value *time.Time) *DepartmentUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *DepartmentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *DepartmentUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *DepartmentCreate) SetNotNilUpdatedAt(value *time.Time) *DepartmentCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *DepartmentUpdate) SetNotNilSort(value *uint32) *DepartmentUpdate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *DepartmentUpdateOne) SetNotNilSort(value *uint32) *DepartmentUpdateOne {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *DepartmentCreate) SetNotNilSort(value *uint32) *DepartmentCreate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *DepartmentUpdate) SetNotNilDepartmentName(value *string) *DepartmentUpdate {
	if value != nil {
		return _m.SetDepartmentName(*value)
	}
	return _m
}

func (_m *DepartmentUpdateOne) SetNotNilDepartmentName(value *string) *DepartmentUpdateOne {
	if value != nil {
		return _m.SetDepartmentName(*value)
	}
	return _m
}

func (_m *DepartmentCreate) SetNotNilDepartmentName(value *string) *DepartmentCreate {
	if value != nil {
		return _m.SetDepartmentName(*value)
	}
	return _m
}

func (_m *DepartmentUpdate) SetNotNilRemark(value *string) *DepartmentUpdate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *DepartmentUpdateOne) SetNotNilRemark(value *string) *DepartmentUpdateOne {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *DepartmentCreate) SetNotNilRemark(value *string) *DepartmentCreate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *DepartmentUpdate) SetNotNilParentID(value *string) *DepartmentUpdate {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

func (_m *DepartmentUpdateOne) SetNotNilParentID(value *string) *DepartmentUpdateOne {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

func (_m *DepartmentCreate) SetNotNilParentID(value *string) *DepartmentCreate {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

func (_m *DepartmentUpdate) SetNotNilIDPath(value *string) *DepartmentUpdate {
	if value != nil {
		return _m.SetIDPath(*value)
	}
	return _m
}

func (_m *DepartmentUpdateOne) SetNotNilIDPath(value *string) *DepartmentUpdateOne {
	if value != nil {
		return _m.SetIDPath(*value)
	}
	return _m
}

func (_m *DepartmentCreate) SetNotNilIDPath(value *string) *DepartmentCreate {
	if value != nil {
		return _m.SetIDPath(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilUpdatedAt(value *time.Time) *MenuUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MenuUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilUpdatedAt(value *time.Time) *MenuCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilSort(value *uint32) *MenuUpdate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilSort(value *uint32) *MenuUpdateOne {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilSort(value *uint32) *MenuCreate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilStatus(value *uint8) *MenuUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilStatus(value *uint8) *MenuUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilStatus(value *uint8) *MenuCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilTitle(value *string) *MenuUpdate {
	if value != nil {
		return _m.SetTitle(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilTitle(value *string) *MenuUpdateOne {
	if value != nil {
		return _m.SetTitle(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilTitle(value *string) *MenuCreate {
	if value != nil {
		return _m.SetTitle(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilIcon(value *string) *MenuUpdate {
	if value != nil {
		return _m.SetIcon(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilIcon(value *string) *MenuUpdateOne {
	if value != nil {
		return _m.SetIcon(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilIcon(value *string) *MenuCreate {
	if value != nil {
		return _m.SetIcon(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilCode(value *string) *MenuUpdate {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilCode(value *string) *MenuUpdateOne {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilCode(value *string) *MenuCreate {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilCodePath(value *string) *MenuUpdate {
	if value != nil {
		return _m.SetCodePath(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilCodePath(value *string) *MenuUpdateOne {
	if value != nil {
		return _m.SetCodePath(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilCodePath(value *string) *MenuCreate {
	if value != nil {
		return _m.SetCodePath(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilParentID(value *string) *MenuUpdate {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilParentID(value *string) *MenuUpdateOne {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilParentID(value *string) *MenuCreate {
	if value != nil {
		return _m.SetParentID(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilMenuType(value *string) *MenuUpdate {
	if value != nil {
		return _m.SetMenuType(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilMenuType(value *string) *MenuUpdateOne {
	if value != nil {
		return _m.SetMenuType(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilMenuType(value *string) *MenuCreate {
	if value != nil {
		return _m.SetMenuType(*value)
	}
	return _m
}

func (_m *MenuUpdate) SetNotNilProperties(value *string) *MenuUpdate {
	if value != nil {
		return _m.SetProperties(*value)
	}
	return _m
}

func (_m *MenuUpdateOne) SetNotNilProperties(value *string) *MenuUpdateOne {
	if value != nil {
		return _m.SetProperties(*value)
	}
	return _m
}

func (_m *MenuCreate) SetNotNilProperties(value *string) *MenuCreate {
	if value != nil {
		return _m.SetProperties(*value)
	}
	return _m
}

func (_m *PositionUpdate) SetNotNilUpdatedAt(value *time.Time) *PositionUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *PositionUpdateOne) SetNotNilUpdatedAt(value *time.Time) *PositionUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *PositionCreate) SetNotNilUpdatedAt(value *time.Time) *PositionCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *PositionUpdate) SetNotNilSort(value *uint32) *PositionUpdate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *PositionUpdateOne) SetNotNilSort(value *uint32) *PositionUpdateOne {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *PositionCreate) SetNotNilSort(value *uint32) *PositionCreate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *PositionUpdate) SetNotNilPositionName(value *string) *PositionUpdate {
	if value != nil {
		return _m.SetPositionName(*value)
	}
	return _m
}

func (_m *PositionUpdateOne) SetNotNilPositionName(value *string) *PositionUpdateOne {
	if value != nil {
		return _m.SetPositionName(*value)
	}
	return _m
}

func (_m *PositionCreate) SetNotNilPositionName(value *string) *PositionCreate {
	if value != nil {
		return _m.SetPositionName(*value)
	}
	return _m
}

func (_m *PositionUpdate) SetNotNilCode(value *string) *PositionUpdate {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *PositionUpdateOne) SetNotNilCode(value *string) *PositionUpdateOne {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *PositionCreate) SetNotNilCode(value *string) *PositionCreate {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *PositionUpdate) SetNotNilRemark(value *string) *PositionUpdate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *PositionUpdateOne) SetNotNilRemark(value *string) *PositionUpdateOne {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *PositionCreate) SetNotNilRemark(value *string) *PositionCreate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *ResourceUpdate) SetNotNilUpdatedAt(value *time.Time) *ResourceUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *ResourceUpdateOne) SetNotNilUpdatedAt(value *time.Time) *ResourceUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *ResourceCreate) SetNotNilUpdatedAt(value *time.Time) *ResourceCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *ResourceUpdate) SetNotNilMethod(value *string) *ResourceUpdate {
	if value != nil {
		return _m.SetMethod(*value)
	}
	return _m
}

func (_m *ResourceUpdateOne) SetNotNilMethod(value *string) *ResourceUpdateOne {
	if value != nil {
		return _m.SetMethod(*value)
	}
	return _m
}

func (_m *ResourceCreate) SetNotNilMethod(value *string) *ResourceCreate {
	if value != nil {
		return _m.SetMethod(*value)
	}
	return _m
}

func (_m *ResourceUpdate) SetNotNilPath(value *string) *ResourceUpdate {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

func (_m *ResourceUpdateOne) SetNotNilPath(value *string) *ResourceUpdateOne {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

func (_m *ResourceCreate) SetNotNilPath(value *string) *ResourceCreate {
	if value != nil {
		return _m.SetPath(*value)
	}
	return _m
}

func (_m *RoleUpdate) SetNotNilUpdatedAt(value *time.Time) *RoleUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *RoleUpdateOne) SetNotNilUpdatedAt(value *time.Time) *RoleUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *RoleCreate) SetNotNilUpdatedAt(value *time.Time) *RoleCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *RoleUpdate) SetNotNilSort(value *uint32) *RoleUpdate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *RoleUpdateOne) SetNotNilSort(value *uint32) *RoleUpdateOne {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *RoleCreate) SetNotNilSort(value *uint32) *RoleCreate {
	if value != nil {
		return _m.SetSort(*value)
	}
	return _m
}

func (_m *RoleUpdate) SetNotNilRoleName(value *string) *RoleUpdate {
	if value != nil {
		return _m.SetRoleName(*value)
	}
	return _m
}

func (_m *RoleUpdateOne) SetNotNilRoleName(value *string) *RoleUpdateOne {
	if value != nil {
		return _m.SetRoleName(*value)
	}
	return _m
}

func (_m *RoleCreate) SetNotNilRoleName(value *string) *RoleCreate {
	if value != nil {
		return _m.SetRoleName(*value)
	}
	return _m
}

func (_m *RoleUpdate) SetNotNilCode(value *string) *RoleUpdate {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *RoleUpdateOne) SetNotNilCode(value *string) *RoleUpdateOne {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *RoleCreate) SetNotNilCode(value *string) *RoleCreate {
	if value != nil {
		return _m.SetCode(*value)
	}
	return _m
}

func (_m *RoleUpdate) SetNotNilRemark(value *string) *RoleUpdate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *RoleUpdateOne) SetNotNilRemark(value *string) *RoleUpdateOne {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *RoleCreate) SetNotNilRemark(value *string) *RoleCreate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilUpdatedAt(value *time.Time) *UserUpdate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilUpdatedAt(value *time.Time) *UserUpdateOne {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilUpdatedAt(value *time.Time) *UserCreate {
	if value != nil {
		return _m.SetUpdatedAt(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilDeletedAt(value *time.Time) *UserUpdate {
	if value != nil {
		return _m.SetDeletedAt(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilDeletedAt(value *time.Time) *UserUpdateOne {
	if value != nil {
		return _m.SetDeletedAt(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilDeletedAt(value *time.Time) *UserCreate {
	if value != nil {
		return _m.SetDeletedAt(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilStatus(value *uint8) *UserUpdate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilStatus(value *uint8) *UserUpdateOne {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilStatus(value *uint8) *UserCreate {
	if value != nil {
		return _m.SetStatus(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilPassword(value *string) *UserUpdate {
	if value != nil {
		return _m.SetPassword(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilPassword(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetPassword(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilPassword(value *string) *UserCreate {
	if value != nil {
		return _m.SetPassword(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilEmail(value *string) *UserUpdate {
	if value != nil {
		return _m.SetEmail(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilEmail(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetEmail(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilEmail(value *string) *UserCreate {
	if value != nil {
		return _m.SetEmail(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilName(value *string) *UserUpdate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilName(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilName(value *string) *UserCreate {
	if value != nil {
		return _m.SetName(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilNickname(value *string) *UserUpdate {
	if value != nil {
		return _m.SetNickname(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilNickname(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetNickname(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilNickname(value *string) *UserCreate {
	if value != nil {
		return _m.SetNickname(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilPhone(value *string) *UserUpdate {
	if value != nil {
		return _m.SetPhone(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilPhone(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetPhone(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilPhone(value *string) *UserCreate {
	if value != nil {
		return _m.SetPhone(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilAvatar(value *string) *UserUpdate {
	if value != nil {
		return _m.SetAvatar(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilAvatar(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetAvatar(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilAvatar(value *string) *UserCreate {
	if value != nil {
		return _m.SetAvatar(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilRemark(value *string) *UserUpdate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilRemark(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilRemark(value *string) *UserCreate {
	if value != nil {
		return _m.SetRemark(*value)
	}
	return _m
}

func (_m *UserUpdate) SetNotNilDepartmentID(value *string) *UserUpdate {
	if value != nil {
		return _m.SetDepartmentID(*value)
	}
	return _m
}

func (_m *UserUpdateOne) SetNotNilDepartmentID(value *string) *UserUpdateOne {
	if value != nil {
		return _m.SetDepartmentID(*value)
	}
	return _m
}

func (_m *UserCreate) SetNotNilDepartmentID(value *string) *UserCreate {
	if value != nil {
		return _m.SetDepartmentID(*value)
	}
	return _m
}
