// Code generated by ent, DO NOT EDIT.

package ent

import "time"

func (d *DepartmentUpdate) SetNotNilUpdatedAt(value *time.Time) *DepartmentUpdate {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

func (d *DepartmentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *DepartmentUpdateOne {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

func (d *DepartmentCreate) SetNotNilUpdatedAt(value *time.Time) *DepartmentCreate {
	if value != nil {
		return d.SetUpdatedAt(*value)
	}
	return d
}

func (d *DepartmentUpdate) SetNotNilSort(value *uint32) *DepartmentUpdate {
	if value != nil {
		return d.SetSort(*value)
	}
	return d
}

func (d *DepartmentUpdateOne) SetNotNilSort(value *uint32) *DepartmentUpdateOne {
	if value != nil {
		return d.SetSort(*value)
	}
	return d
}

func (d *DepartmentCreate) SetNotNilSort(value *uint32) *DepartmentCreate {
	if value != nil {
		return d.SetSort(*value)
	}
	return d
}

func (d *DepartmentUpdate) SetNotNilDepartmentName(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetDepartmentName(*value)
	}
	return d
}

func (d *DepartmentUpdateOne) SetNotNilDepartmentName(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetDepartmentName(*value)
	}
	return d
}

func (d *DepartmentCreate) SetNotNilDepartmentName(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetDepartmentName(*value)
	}
	return d
}

func (d *DepartmentUpdate) SetNotNilRemark(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetRemark(*value)
	}
	return d
}

func (d *DepartmentUpdateOne) SetNotNilRemark(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetRemark(*value)
	}
	return d
}

func (d *DepartmentCreate) SetNotNilRemark(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetRemark(*value)
	}
	return d
}

func (d *DepartmentUpdate) SetNotNilParentID(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetParentID(*value)
	}
	return d
}

func (d *DepartmentUpdateOne) SetNotNilParentID(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetParentID(*value)
	}
	return d
}

func (d *DepartmentCreate) SetNotNilParentID(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetParentID(*value)
	}
	return d
}

func (d *DepartmentUpdate) SetNotNilIDPath(value *string) *DepartmentUpdate {
	if value != nil {
		return d.SetIDPath(*value)
	}
	return d
}

func (d *DepartmentUpdateOne) SetNotNilIDPath(value *string) *DepartmentUpdateOne {
	if value != nil {
		return d.SetIDPath(*value)
	}
	return d
}

func (d *DepartmentCreate) SetNotNilIDPath(value *string) *DepartmentCreate {
	if value != nil {
		return d.SetIDPath(*value)
	}
	return d
}

func (m *MenuUpdate) SetNotNilUpdatedAt(value *time.Time) *MenuUpdate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilUpdatedAt(value *time.Time) *MenuUpdateOne {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilUpdatedAt(value *time.Time) *MenuCreate {
	if value != nil {
		return m.SetUpdatedAt(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilSort(value *uint32) *MenuUpdate {
	if value != nil {
		return m.SetSort(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilSort(value *uint32) *MenuUpdateOne {
	if value != nil {
		return m.SetSort(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilSort(value *uint32) *MenuCreate {
	if value != nil {
		return m.SetSort(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilStatus(value *uint8) *MenuUpdate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilStatus(value *uint8) *MenuUpdateOne {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilStatus(value *uint8) *MenuCreate {
	if value != nil {
		return m.SetStatus(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilTitle(value *string) *MenuUpdate {
	if value != nil {
		return m.SetTitle(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilTitle(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetTitle(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilTitle(value *string) *MenuCreate {
	if value != nil {
		return m.SetTitle(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilIcon(value *string) *MenuUpdate {
	if value != nil {
		return m.SetIcon(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilIcon(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetIcon(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilIcon(value *string) *MenuCreate {
	if value != nil {
		return m.SetIcon(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilCode(value *string) *MenuUpdate {
	if value != nil {
		return m.SetCode(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilCode(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetCode(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilCode(value *string) *MenuCreate {
	if value != nil {
		return m.SetCode(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilCodePath(value *string) *MenuUpdate {
	if value != nil {
		return m.SetCodePath(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilCodePath(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetCodePath(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilCodePath(value *string) *MenuCreate {
	if value != nil {
		return m.SetCodePath(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilParentID(value *string) *MenuUpdate {
	if value != nil {
		return m.SetParentID(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilParentID(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetParentID(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilParentID(value *string) *MenuCreate {
	if value != nil {
		return m.SetParentID(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilMenuType(value *string) *MenuUpdate {
	if value != nil {
		return m.SetMenuType(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilMenuType(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetMenuType(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilMenuType(value *string) *MenuCreate {
	if value != nil {
		return m.SetMenuType(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilMenuPath(value *string) *MenuUpdate {
	if value != nil {
		return m.SetMenuPath(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilMenuPath(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetMenuPath(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilMenuPath(value *string) *MenuCreate {
	if value != nil {
		return m.SetMenuPath(*value)
	}
	return m
}

func (m *MenuUpdate) SetNotNilProperties(value *string) *MenuUpdate {
	if value != nil {
		return m.SetProperties(*value)
	}
	return m
}

func (m *MenuUpdateOne) SetNotNilProperties(value *string) *MenuUpdateOne {
	if value != nil {
		return m.SetProperties(*value)
	}
	return m
}

func (m *MenuCreate) SetNotNilProperties(value *string) *MenuCreate {
	if value != nil {
		return m.SetProperties(*value)
	}
	return m
}

func (po *PositionUpdate) SetNotNilUpdatedAt(value *time.Time) *PositionUpdate {
	if value != nil {
		return po.SetUpdatedAt(*value)
	}
	return po
}

func (po *PositionUpdateOne) SetNotNilUpdatedAt(value *time.Time) *PositionUpdateOne {
	if value != nil {
		return po.SetUpdatedAt(*value)
	}
	return po
}

func (po *PositionCreate) SetNotNilUpdatedAt(value *time.Time) *PositionCreate {
	if value != nil {
		return po.SetUpdatedAt(*value)
	}
	return po
}

func (po *PositionUpdate) SetNotNilSort(value *uint32) *PositionUpdate {
	if value != nil {
		return po.SetSort(*value)
	}
	return po
}

func (po *PositionUpdateOne) SetNotNilSort(value *uint32) *PositionUpdateOne {
	if value != nil {
		return po.SetSort(*value)
	}
	return po
}

func (po *PositionCreate) SetNotNilSort(value *uint32) *PositionCreate {
	if value != nil {
		return po.SetSort(*value)
	}
	return po
}

func (po *PositionUpdate) SetNotNilPositionName(value *string) *PositionUpdate {
	if value != nil {
		return po.SetPositionName(*value)
	}
	return po
}

func (po *PositionUpdateOne) SetNotNilPositionName(value *string) *PositionUpdateOne {
	if value != nil {
		return po.SetPositionName(*value)
	}
	return po
}

func (po *PositionCreate) SetNotNilPositionName(value *string) *PositionCreate {
	if value != nil {
		return po.SetPositionName(*value)
	}
	return po
}

func (po *PositionUpdate) SetNotNilCode(value *string) *PositionUpdate {
	if value != nil {
		return po.SetCode(*value)
	}
	return po
}

func (po *PositionUpdateOne) SetNotNilCode(value *string) *PositionUpdateOne {
	if value != nil {
		return po.SetCode(*value)
	}
	return po
}

func (po *PositionCreate) SetNotNilCode(value *string) *PositionCreate {
	if value != nil {
		return po.SetCode(*value)
	}
	return po
}

func (po *PositionUpdate) SetNotNilRemark(value *string) *PositionUpdate {
	if value != nil {
		return po.SetRemark(*value)
	}
	return po
}

func (po *PositionUpdateOne) SetNotNilRemark(value *string) *PositionUpdateOne {
	if value != nil {
		return po.SetRemark(*value)
	}
	return po
}

func (po *PositionCreate) SetNotNilRemark(value *string) *PositionCreate {
	if value != nil {
		return po.SetRemark(*value)
	}
	return po
}

func (r *ResourceUpdate) SetNotNilUpdatedAt(value *time.Time) *ResourceUpdate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

func (r *ResourceUpdateOne) SetNotNilUpdatedAt(value *time.Time) *ResourceUpdateOne {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

func (r *ResourceCreate) SetNotNilUpdatedAt(value *time.Time) *ResourceCreate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

func (r *ResourceUpdate) SetNotNilMethod(value *string) *ResourceUpdate {
	if value != nil {
		return r.SetMethod(*value)
	}
	return r
}

func (r *ResourceUpdateOne) SetNotNilMethod(value *string) *ResourceUpdateOne {
	if value != nil {
		return r.SetMethod(*value)
	}
	return r
}

func (r *ResourceCreate) SetNotNilMethod(value *string) *ResourceCreate {
	if value != nil {
		return r.SetMethod(*value)
	}
	return r
}

func (r *ResourceUpdate) SetNotNilPath(value *string) *ResourceUpdate {
	if value != nil {
		return r.SetPath(*value)
	}
	return r
}

func (r *ResourceUpdateOne) SetNotNilPath(value *string) *ResourceUpdateOne {
	if value != nil {
		return r.SetPath(*value)
	}
	return r
}

func (r *ResourceCreate) SetNotNilPath(value *string) *ResourceCreate {
	if value != nil {
		return r.SetPath(*value)
	}
	return r
}

func (r *RoleUpdate) SetNotNilUpdatedAt(value *time.Time) *RoleUpdate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

func (r *RoleUpdateOne) SetNotNilUpdatedAt(value *time.Time) *RoleUpdateOne {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

func (r *RoleCreate) SetNotNilUpdatedAt(value *time.Time) *RoleCreate {
	if value != nil {
		return r.SetUpdatedAt(*value)
	}
	return r
}

func (r *RoleUpdate) SetNotNilSort(value *uint32) *RoleUpdate {
	if value != nil {
		return r.SetSort(*value)
	}
	return r
}

func (r *RoleUpdateOne) SetNotNilSort(value *uint32) *RoleUpdateOne {
	if value != nil {
		return r.SetSort(*value)
	}
	return r
}

func (r *RoleCreate) SetNotNilSort(value *uint32) *RoleCreate {
	if value != nil {
		return r.SetSort(*value)
	}
	return r
}

func (r *RoleUpdate) SetNotNilRoleName(value *string) *RoleUpdate {
	if value != nil {
		return r.SetRoleName(*value)
	}
	return r
}

func (r *RoleUpdateOne) SetNotNilRoleName(value *string) *RoleUpdateOne {
	if value != nil {
		return r.SetRoleName(*value)
	}
	return r
}

func (r *RoleCreate) SetNotNilRoleName(value *string) *RoleCreate {
	if value != nil {
		return r.SetRoleName(*value)
	}
	return r
}

func (r *RoleUpdate) SetNotNilCode(value *string) *RoleUpdate {
	if value != nil {
		return r.SetCode(*value)
	}
	return r
}

func (r *RoleUpdateOne) SetNotNilCode(value *string) *RoleUpdateOne {
	if value != nil {
		return r.SetCode(*value)
	}
	return r
}

func (r *RoleCreate) SetNotNilCode(value *string) *RoleCreate {
	if value != nil {
		return r.SetCode(*value)
	}
	return r
}

func (r *RoleUpdate) SetNotNilRemark(value *string) *RoleUpdate {
	if value != nil {
		return r.SetRemark(*value)
	}
	return r
}

func (r *RoleUpdateOne) SetNotNilRemark(value *string) *RoleUpdateOne {
	if value != nil {
		return r.SetRemark(*value)
	}
	return r
}

func (r *RoleCreate) SetNotNilRemark(value *string) *RoleCreate {
	if value != nil {
		return r.SetRemark(*value)
	}
	return r
}

func (u *UserUpdate) SetNotNilUpdatedAt(value *time.Time) *UserUpdate {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilUpdatedAt(value *time.Time) *UserUpdateOne {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilUpdatedAt(value *time.Time) *UserCreate {
	if value != nil {
		return u.SetUpdatedAt(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilDeletedAt(value *time.Time) *UserUpdate {
	if value != nil {
		return u.SetDeletedAt(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilDeletedAt(value *time.Time) *UserUpdateOne {
	if value != nil {
		return u.SetDeletedAt(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilDeletedAt(value *time.Time) *UserCreate {
	if value != nil {
		return u.SetDeletedAt(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilStatus(value *uint8) *UserUpdate {
	if value != nil {
		return u.SetStatus(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilStatus(value *uint8) *UserUpdateOne {
	if value != nil {
		return u.SetStatus(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilStatus(value *uint8) *UserCreate {
	if value != nil {
		return u.SetStatus(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilPassword(value *string) *UserUpdate {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilPassword(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilPassword(value *string) *UserCreate {
	if value != nil {
		return u.SetPassword(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilEmail(value *string) *UserUpdate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilEmail(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilEmail(value *string) *UserCreate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilName(value *string) *UserUpdate {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilName(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilName(value *string) *UserCreate {
	if value != nil {
		return u.SetName(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilNickname(value *string) *UserUpdate {
	if value != nil {
		return u.SetNickname(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilNickname(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetNickname(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilNickname(value *string) *UserCreate {
	if value != nil {
		return u.SetNickname(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilPhone(value *string) *UserUpdate {
	if value != nil {
		return u.SetPhone(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilPhone(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetPhone(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilPhone(value *string) *UserCreate {
	if value != nil {
		return u.SetPhone(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilAvatar(value *string) *UserUpdate {
	if value != nil {
		return u.SetAvatar(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilAvatar(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetAvatar(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilAvatar(value *string) *UserCreate {
	if value != nil {
		return u.SetAvatar(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilRemark(value *string) *UserUpdate {
	if value != nil {
		return u.SetRemark(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilRemark(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetRemark(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilRemark(value *string) *UserCreate {
	if value != nil {
		return u.SetRemark(*value)
	}
	return u
}

func (u *UserUpdate) SetNotNilDepartmentID(value *string) *UserUpdate {
	if value != nil {
		return u.SetDepartmentID(*value)
	}
	return u
}

func (u *UserUpdateOne) SetNotNilDepartmentID(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetDepartmentID(*value)
	}
	return u
}

func (u *UserCreate) SetNotNilDepartmentID(value *string) *UserCreate {
	if value != nil {
		return u.SetDepartmentID(*value)
	}
	return u
}
