package msgc

const (
	REDIS_ERROR            = "REDIS_ERROR"
	DB_INIT_ERROR          = "INIT_ERROR"
	ENT_UNKNOWN_ERROR      = "UNKNOWN_ERROR"
	ENT_VALIDATION_ERROR   = "VALIDATION_ERROR"
	ENT_NOTFOUND_ERROR     = "NOTFOUND_ERROR"
	ENT_NOT_SINGULAR_ERROR = "NOT_SINGULAR_ERROR"
	ENT_NOT_LOADED_ERROR   = "NOT_LOADED_ERROR"
	ENT_CONSTRAINT_ERROR   = "CONSTRAINT_ERROR"

	SUCCESS        = "SUCCESS"
	FAILED         = "FAILED"
	CREATE_SUCCESS = "CREATE_SUCCESS"
	CREATE_FAILED  = "CREATE_FAILED"
	DELETE_SUCCESS = "DELETE_SUCCESS"
	DELETE_FAILED  = "DELETE_FAILED"
	UPDATE_SUCCESS = "UPDATE_SUCCESS"
	UPDATE_FAILED  = "UPDATE_FAILED"
)
