package msgc

const (
	APP_NOTALLOWED     = "APP_NOTALLOWED"
	TOKEN_INVALID      = "TOKEN_INVALID"
	AUTH_NOTALLOWED    = "AUTH_NOTALLOWED"
	VALIDATE_FAIL      = "VALIDATE_FAIL"
	TOKEN_REFRESH_FAIL = "TOKEN_REFRESH_FAIL"
	USER_BANNED        = "USER_BANNED"
	PASSWORD_ERROR     = "PASSWORD_ERROR"
	CONFIRM_ERROR      = "CONFIRM_ERROR"
)
