package msgc

const (
	APP_NOTALLOWED      = "APP_NOTALLOWED"
	AUTH_NOTALLOWED     = "AUTH_NOTALLOWED"
	VALIDATE_FAILURE    = "VALIDATE_FAILURE"
	TOKEN_REFRESH_ERROR = "TOKEN_REFRESH_ERROR"
	USER_BANNED         = "USER_BANNED"
	PASSWORD_ERROR      = "PASSWORD_ERROR"
	CONFIRM_ERROR       = "CONFIRM_ERROR"
)
