// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	admin_systemaccount "github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/handler/admin_system/account"
	admin_systembase "github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/handler/admin_system/base"
	admin_systemdepartment "github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/handler/admin_system/department"
	admin_systemmenu "github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/handler/admin_system/menu"
	admin_systemposition "github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/handler/admin_system/position"
	admin_systemrole "github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/handler/admin_system/role"
	admin_systemuser "github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/handler/admin_system/user"
	"github.com/DrReMain/cyber-ecosystem-server/api/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 使用邮箱和密码登录
				Method:  http.MethodPost,
				Path:    "/login_password",
				Handler: admin_systemaccount.LoginPasswordHandler(serverCtx),
			},
			{
				// 刷新访问令牌
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: admin_systemaccount.RefreshHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin_system/account"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 初始化系统
				Method:  http.MethodPost,
				Path:    "/init",
				Handler: admin_systembase.InitHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin_system/base"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建部门
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admin_systemdepartment.CreateDepartmentHandler(serverCtx),
				},
				{
					// 查询部门列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: admin_systemdepartment.QueryDepartmentHandler(serverCtx),
				},
				{
					// 删除单个部门
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admin_systemdepartment.DeleteDepartmentOneHandler(serverCtx),
				},
				{
					// 更新部门
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: admin_systemdepartment.UpdateDepartmentHandler(serverCtx),
				},
				{
					// 获取部门详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: admin_systemdepartment.GetDepartmentHandler(serverCtx),
				},
				{
					// 删除部门
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: admin_systemdepartment.DeleteDepartmentHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin_system/department"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建菜单
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admin_systemmenu.CreateMenuHandler(serverCtx),
				},
				{
					// 查询菜单列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: admin_systemmenu.QueryMenuHandler(serverCtx),
				},
				{
					// 删除单个菜单
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admin_systemmenu.DeleteMenuOneHandler(serverCtx),
				},
				{
					// 更新菜单
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: admin_systemmenu.UpdateMenuHandler(serverCtx),
				},
				{
					// 获取菜单详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: admin_systemmenu.GetMenuHandler(serverCtx),
				},
				{
					// 删除菜单
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: admin_systemmenu.DeleteMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin_system/menu"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建职位
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admin_systemposition.CreatePositionHandler(serverCtx),
				},
				{
					// 查询职位列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: admin_systemposition.QueryPositionHandler(serverCtx),
				},
				{
					// 删除单个职位
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admin_systemposition.DeletePositionOneHandler(serverCtx),
				},
				{
					// 更新职位
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: admin_systemposition.UpdatePositionHandler(serverCtx),
				},
				{
					// 获取职位详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: admin_systemposition.GetPositionHandler(serverCtx),
				},
				{
					// 删除职位
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: admin_systemposition.DeletePositionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin_system/position"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建角色
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admin_systemrole.CreateRoleHandler(serverCtx),
				},
				{
					// 查询角色列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: admin_systemrole.QueryRoleHandler(serverCtx),
				},
				{
					// 删除单个角色
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admin_systemrole.DeleteRoleOneHandler(serverCtx),
				},
				{
					// 更新角色
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: admin_systemrole.UpdateRoleHandler(serverCtx),
				},
				{
					// 获取角色详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: admin_systemrole.GetRoleHandler(serverCtx),
				},
				{
					// 删除角色
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: admin_systemrole.DeleteRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin_system/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建用户
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admin_systemuser.CreateUserHandler(serverCtx),
				},
				{
					// 查询用户列表
					Method:  http.MethodGet,
					Path:    "/",
					Handler: admin_systemuser.QueryUserHandler(serverCtx),
				},
				{
					// 删除单个用户
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admin_systemuser.DeleteUserOneHandler(serverCtx),
				},
				{
					// 更新用户
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: admin_systemuser.UpdateUserHandler(serverCtx),
				},
				{
					// 获取用户详情
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: admin_systemuser.GetUserHandler(serverCtx),
				},
				{
					// 通过邮箱获取用户
					Method:  http.MethodGet,
					Path:    "/byemail",
					Handler: admin_systemuser.GetUserByEmailHandler(serverCtx),
				},
				{
					// 删除用户
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: admin_systemuser.DeleteUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin_system/user"),
	)
}
