// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin_system.proto

package roleservice

import (
	"context"

	"github.com/DrReMain/cyber-ecosystem-server/rpc/admin_system/admin_system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDRes             = admin_system.BaseIDRes
	BaseRes               = admin_system.BaseRes
	CasbinBody            = admin_system.CasbinBody
	CasbinReq             = admin_system.CasbinReq
	CasbinRes             = admin_system.CasbinRes
	DepartmentBody        = admin_system.DepartmentBody
	DepartmentListReq     = admin_system.DepartmentListReq
	DepartmentListRes     = admin_system.DepartmentListRes
	EmailReq              = admin_system.EmailReq
	Empty                 = admin_system.Empty
	IDReq                 = admin_system.IDReq
	IDsReq                = admin_system.IDsReq
	ListReq               = admin_system.ListReq
	MenuBody              = admin_system.MenuBody
	MenuListByRoleCodeReq = admin_system.MenuListByRoleCodeReq
	MenuListReq           = admin_system.MenuListReq
	MenuListRes           = admin_system.MenuListRes
	PositionBody          = admin_system.PositionBody
	PositionListReq       = admin_system.PositionListReq
	PositionListRes       = admin_system.PositionListRes
	ResourceBody          = admin_system.ResourceBody
	RoleBody              = admin_system.RoleBody
	RoleFromMenuReq       = admin_system.RoleFromMenuReq
	RoleFromMenuRes       = admin_system.RoleFromMenuRes
	RoleFromRoleReq       = admin_system.RoleFromRoleReq
	RoleFromRoleRes       = admin_system.RoleFromRoleRes
	RoleListReq           = admin_system.RoleListReq
	RoleListRes           = admin_system.RoleListRes
	UserBody              = admin_system.UserBody
	UserListReq           = admin_system.UserListReq
	UserListRes           = admin_system.UserListRes

	RoleService interface {
		CreateRole(ctx context.Context, in *RoleBody, opts ...grpc.CallOption) (*BaseIDRes, error)
		DeleteRole(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseRes, error)
		UpdateRole(ctx context.Context, in *RoleBody, opts ...grpc.CallOption) (*BaseRes, error)
		GetRole(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*RoleBody, error)
		QueryRole(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListRes, error)
	}

	defaultRoleService struct {
		cli zrpc.Client
	}
)

func NewRoleService(cli zrpc.Client) RoleService {
	return &defaultRoleService{
		cli: cli,
	}
}

func (m *defaultRoleService) CreateRole(ctx context.Context, in *RoleBody, opts ...grpc.CallOption) (*BaseIDRes, error) {
	client := admin_system.NewRoleServiceClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultRoleService) DeleteRole(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseRes, error) {
	client := admin_system.NewRoleServiceClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultRoleService) UpdateRole(ctx context.Context, in *RoleBody, opts ...grpc.CallOption) (*BaseRes, error) {
	client := admin_system.NewRoleServiceClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRoleService) GetRole(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*RoleBody, error) {
	client := admin_system.NewRoleServiceClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultRoleService) QueryRole(ctx context.Context, in *RoleListReq, opts ...grpc.CallOption) (*RoleListRes, error) {
	client := admin_system.NewRoleServiceClient(m.cli.Conn())
	return client.QueryRole(ctx, in, opts...)
}
