// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin_system.proto

package server

import (
	"context"

	"github.com/DrReMain/cyber-ecosystem-server/rpc/admin_system/admin_system"
	"github.com/DrReMain/cyber-ecosystem-server/rpc/admin_system/internal/logic/baseservice"
	"github.com/DrReMain/cyber-ecosystem-server/rpc/admin_system/internal/svc"
)

type BaseServiceServer struct {
	svcCtx *svc.ServiceContext
	admin_system.UnimplementedBaseServiceServer
}

func NewBaseServiceServer(svcCtx *svc.ServiceContext) *BaseServiceServer {
	return &BaseServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BaseServiceServer) InitDB(ctx context.Context, in *admin_system.Empty) (*admin_system.BaseRes, error) {
	l := baseservicelogic.NewInitDBLogic(ctx, s.svcCtx)
	return l.InitDB(in)
}
