// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin_system.proto

package departmentservice

import (
	"context"

	"github.com/DrReMain/cyber-ecosystem-server/rpc/admin_system/admin_system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDRes             = admin_system.BaseIDRes
	BaseRes               = admin_system.BaseRes
	CasbinBody            = admin_system.CasbinBody
	CasbinReq             = admin_system.CasbinReq
	CasbinRes             = admin_system.CasbinRes
	DepartmentBody        = admin_system.DepartmentBody
	DepartmentListReq     = admin_system.DepartmentListReq
	DepartmentListRes     = admin_system.DepartmentListRes
	EmailReq              = admin_system.EmailReq
	Empty                 = admin_system.Empty
	IDReq                 = admin_system.IDReq
	IDsReq                = admin_system.IDsReq
	ListReq               = admin_system.ListReq
	MenuBody              = admin_system.MenuBody
	MenuListByRoleCodeReq = admin_system.MenuListByRoleCodeReq
	MenuListReq           = admin_system.MenuListReq
	MenuListRes           = admin_system.MenuListRes
	PositionBody          = admin_system.PositionBody
	PositionListReq       = admin_system.PositionListReq
	PositionListRes       = admin_system.PositionListRes
	ResourceBody          = admin_system.ResourceBody
	RoleBody              = admin_system.RoleBody
	RoleFromMenuReq       = admin_system.RoleFromMenuReq
	RoleFromMenuRes       = admin_system.RoleFromMenuRes
	RoleFromRoleReq       = admin_system.RoleFromRoleReq
	RoleFromRoleRes       = admin_system.RoleFromRoleRes
	RoleListReq           = admin_system.RoleListReq
	RoleListRes           = admin_system.RoleListRes
	UserBody              = admin_system.UserBody
	UserListReq           = admin_system.UserListReq
	UserListRes           = admin_system.UserListRes

	DepartmentService interface {
		CreateDepartment(ctx context.Context, in *DepartmentBody, opts ...grpc.CallOption) (*BaseIDRes, error)
		DeleteDepartment(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseRes, error)
		UpdateDepartment(ctx context.Context, in *DepartmentBody, opts ...grpc.CallOption) (*BaseRes, error)
		GetDepartment(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*DepartmentBody, error)
		QueryDepartment(ctx context.Context, in *DepartmentListReq, opts ...grpc.CallOption) (*DepartmentListRes, error)
	}

	defaultDepartmentService struct {
		cli zrpc.Client
	}
)

func NewDepartmentService(cli zrpc.Client) DepartmentService {
	return &defaultDepartmentService{
		cli: cli,
	}
}

func (m *defaultDepartmentService) CreateDepartment(ctx context.Context, in *DepartmentBody, opts ...grpc.CallOption) (*BaseIDRes, error) {
	client := admin_system.NewDepartmentServiceClient(m.cli.Conn())
	return client.CreateDepartment(ctx, in, opts...)
}

func (m *defaultDepartmentService) DeleteDepartment(ctx context.Context, in *IDsReq, opts ...grpc.CallOption) (*BaseRes, error) {
	client := admin_system.NewDepartmentServiceClient(m.cli.Conn())
	return client.DeleteDepartment(ctx, in, opts...)
}

func (m *defaultDepartmentService) UpdateDepartment(ctx context.Context, in *DepartmentBody, opts ...grpc.CallOption) (*BaseRes, error) {
	client := admin_system.NewDepartmentServiceClient(m.cli.Conn())
	return client.UpdateDepartment(ctx, in, opts...)
}

func (m *defaultDepartmentService) GetDepartment(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*DepartmentBody, error) {
	client := admin_system.NewDepartmentServiceClient(m.cli.Conn())
	return client.GetDepartment(ctx, in, opts...)
}

func (m *defaultDepartmentService) QueryDepartment(ctx context.Context, in *DepartmentListReq, opts ...grpc.CallOption) (*DepartmentListRes, error) {
	client := admin_system.NewDepartmentServiceClient(m.cli.Conn())
	return client.QueryDepartment(ctx, in, opts...)
}
